-- Represents the user's fridge configuration
CREATE TABLE TFA_fridges (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Represents clickable sections on the fridge image (generated by AI)
CREATE TABLE TFA_areas (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  fridge_id UUID REFERENCES TFA_fridges(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  coordinates JSONB NOT NULL, -- { ymin, xmin, ymax, xmax } relative to image
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Represents items currently in the fridge
CREATE TABLE TFA_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  area_id UUID REFERENCES TFA_areas(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  quantity INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Represents the catalog of previously identified items
CREATE TABLE TFA_item_catalog (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  last_used_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
